export const ME_ACTION_TYPES = {
  UPDATE_ME_START: 'me/UPDATE_ME_START',
  UPDATE_ME_SUCCESS: 'me/UPDATE_ME_SUCCESS',
  UPDATE_ME_FAILED: 'me/UPDATE_ME_FAILED',
  UPDATE_PASSWORD_START: 'me/UPDATE_PASSWORD_START',
  UPDATE_PASSWORD_SUCCESS: 'me/UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAILED: 'me/UPDATE_PASSWORD_FAILED',
  LOGOUT_START: 'me/LOGOUT_START',
  LOGOUT_SUCCESS: 'me/LOGOUT_SUCCESS',
  LOGOUT_FAILED: 'me/LOGOUT_FAILED',
  SET_ACTIVE_SETTING: 'me/SET_ACTIVE_SETTING',
};
