export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: 'user/SET_CURRENT_USER',
  LOGIN_USER_START: 'user/LOGIN_USER_START',
  LOGIN_USER_SUCCESS: 'user/LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILED: 'user/LOGIN_USER_FAILED',
  SIGNUP_USER_START: 'user/SIGNUP_USER_START',
  SIGNUP_USER_SUCCESS: 'user/SIGNUP_USER_SUCCESS',
  SIGNUP_USER_FAILED: 'user/SIGNUP_USER_FAILED',
};
