export const MENU_ACTION_TYPES = {
  FETCH_MENU_ITEMS_START: 'menu/FETCH_MENU_ITEMS_START',
  FETCH_MENU_ITEMS_SUCCESS: 'menu/FETCH_MENU_ITEMS_SUCCESS',
  FETCH_MENU_ITEMS_FAILED: 'menu/FETCH_MENU_ITEMS_FAILED',
  CHANGE_DISPLAY_ITEMS: 'menu/CHANGE_DISPLAY_ITEMS',
  FETCH_MENU_ITEM_START: 'menu/FETCH_MENU_ITEM_START',
  FETCH_MENU_ITEM_SUCCESS: 'menu/FETCH_MENU_ITEM_SUCCESS',
  FETCH_MENU_ITEM_FAILED: 'menu/FETCH_MENU_ITEM_FAILED',
  POST_REVIEW_START: 'menu/POST_REVIEW_START',
  POST_REVIEW_SUCCESS: 'menu/POST_REVIEW_SUCCESS',
  POST_REVIEW_FAILED: 'menu/POST_REVIEW_SFAILED',
};
